### ISSUE TITLE
Font size in iOS Apple Books

### ISSUE THREAD

**Issue by mermare** [bartificer/taming-the-terminal#74]
I cannot make the font size larger in iOS. I tried changing it to San Francisco from Original but still very small at maximum setting. 

![15B34F34-755A-4392-8453-A488C2DA49AA](https://user-images.githubusercontent.com/3846645/89340535-e3cf1480-d66d-11ea-8631-4249c92f6329.jpeg)

**Comment by hepabolu** [comment]
@mermare The font resizing should be fixed now. You can test it by downloading the ePub file from the release section: https://github.com/bartificer/taming-the-terminal/releases/latest
