### ISSUE TITLE
INSTALLATION.md

### ISSUE THREAD

**Issue by frankocarroll** [bartificer/taming-the-terminal#75]
Hi Helma,
I tried out the steps in INSTALLATION.md and have some suggestions for updates in that file.
I've never used node or ruby or kramdoc before so had to start at the beginning of the instructions to get them, which was fine.

### Repository Name Change?
Now that the repository has been renamed I think that
```shell
git clone https://github.com/hepabolu/ttt.git
```
should be
```shell
git clone https://github.com/bartificer/taming-the-terminal.git
```
instead (although ...`/hepabolu/ttt.git` redirects to the new location). I used the `bartificer` link directly and it seemed to clone fine. I followed all the install directions and came across a couple of issues.

### Bundle instead of gem?
This did not work for me
```shell
bash-3.2$ gem install
ERROR:  While executing gem ... (Gem::CommandLineError)
    Please specify at least one gem name (e.g. gem build GEMNAME)
```
I had to say
```shell
bundle install
```
instead.

### Extra npm modules needed for tttconvert?
Having got this far, I downloaded Bart's episode 39 and tried to convert it
````shell
bash-3.2$ wc *.html
     553    4769   60648 TTT Part 39 of n – Advanced TMUX : Bart Busschots.html
bash-3.2$ wc -m *html
   60629 TTT Part 39 of n – Advanced TMUX : Bart Busschots.html
bash-3.2$ cd ../tttconvert/
bash-3.2$ ./ttconvert.sh 39
/Users/ocarroll/Dev/TTT/taming-the-terminal/tttconvert
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /Users/ocarroll/Dev/TTT/taming-the-term/tttconvert/index.js
````
etc. Taking a guess I tried

````
bash-3.2$ npm list
ttt@1.0.0 /Users/ocarroll/Dev/TTT/taming-the-terminal/tttconvert
├─┬ UNMET DEPENDENCY chalk@4.0.0
│ ├─┬ UNMET DEPENDENCY ansi-styles@4.2.1
...
````
so then I tried
````
bash-3.2$ pwd
/Users/ocarroll/Dev/TTT/taming-the-terminal/tttconvert
bash-3.2$ ls
LICENSE                 package-lock.json       tttconvert.sh
README.md               package.json            tttconvert.tap
index.js                tt.sh
lib                     tttconvert.index
bash-3.2$ npm install
````
And that fixed the problem. 

Later, `kramdoc` worked perfectly finally I could generate a `*.adoc` file. Hooray!

### Comparing output at this stage in the process?
Then I noticed that `diff` says the my new `adoc` is subtly different on many lines from the final `adoc` in the repository. Maybe Bart has edited his source html or maybe there are more transformations to come? Is it expected to be different at this stage of the conversion? Or has the final file been proofread and manually tweaked?

````
franks-mbp:convert2 ocarroll$ diff ttt39.adoc ../book/ttt39.adoc | head
1c1,3
< = TTT Part 39 of n -- Advanced TMUX
---
> [[ttt39]]
> = TTT Part 39 of n {longdash} Advanced TMUX
> include::variables.adoc[]
3c5
< In the previous instalment we learned how to use the `tmux` as a replacement for the `screen` command which has been deprecated on RedHat Enterprise Linux (and hence CentOS too). In this instalment we'll take TMUX to the next level, making use of the fact that a single TMUX session can contain arbitrarily many windows, each consisting of arbitrarily many panes.
---
> In the previous instalment we learned how to use the `tmux` command as a replacement for the `screen` command which has been deprecated on RedHat Enterprise Linux (and hence CentOS as well.) In this instalment we'll take TMUX to the next level, making use of the fact that a single TMUX session can contain arbitrarily many windows, each consisting of arbitrarily many panes.
````

That's as far as I have got so far, thought I would report these differences.

**Comment by hepabolu** [comment]
Thanks for taking the time to actually follow the steps. I've added your comments to the file. Re your last comment: yes it's expected that the diff will show differences. The final book/*.adoc files have all been proofread and tweaked by hand.
