### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by frankocarroll** [bartificer/taming-the-terminal#80]
Hi there,

I have some typo fixes to the book/adoc files.

may I have permission (temporary OK) as collaborator to do a `git push` to taming-the-terminal or do you prefer I should fork and then submit pull request?

patches are attached. Primarily corrections of "it's" to possesive "its" in the right places, plus a couple of missing words  here and there.
[patch.txt](https://github.com/bartificer/taming-the-terminal/files/5085060/patch.txt)

Regards
Frank O'Carroll

**Comment by hepabolu** [comment]
@frankocarroll could you please make it into a pull request?

**Comment by hepabolu** [comment]
Never mind, I applied your patch. Thank you.
