### ISSUE TITLE
Upload update 1.3 to Apple Books

### ISSUE THREAD

**Issue by NosillaCast** [bartificer/taming-the-terminal#84]
Finished uploading the book and new cover art to Apple Books for Authors. I wrote some notes in the wiki but I'd like to include screenshots. Wiki makes you put the files somewhere in order to reference them by URL. Is there a preferred spot in this repository where I can put them? Or do I just make a directory and then reference it?

btw, Update is not showing in the Book Store yet.

**Comment by NosillaCast** [comment]
Update - book did get updated in Apple Books, but somehow I managed to only update the cover. Trying again.

**Comment by hepabolu** [comment]
The wiki is a separate repository, called taming-the-terminal.wiki
![image](https://user-images.githubusercontent.com/7474858/90594538-f4919580-e1ea-11ea-83e8-ef1c898a2f26.jpeg)

I have already created a folder called 'images' where you can add images to reference in the wiki pages.

**Comment by hepabolu** [comment]
Version 1.3 is available in the Apple Books store
