### ISSUE TITLE
Still cannot increase the text size despite update to 1.3

### ISSUE THREAD

**Issue by mermare** [bartificer/taming-the-terminal#85]
I updated the book in iOS Books app to v. 1.3 (8-18-20) and still have the same issue where I cannot increase the text size as in the closed issue here: https://github.com/bartificer/taming-the-terminal/issues/74#issue-673054926

I quit Books and reopened but the issue persists.

**Comment by hepabolu** [comment]
The code is fixed. Font resizing should be possible.
